ストレージに保存する処理を抽象化
indoor-m/hotcale pull request #36
Opened 2022-01-13 18:31 UTC by K-shir0

### 主な変更

- `ChromeStorageObject` を追加して抽象化を可能にしました。またそれらに準ずるメソッドを作成しました。

### 確認方法

確認方法が分からないのでお願いしたいです。

2022-01-14 08:39 UTC, tingtt requested changes

2022-01-14 08:39 UTC, tingtt commented on src/utils/base/chromeStorage.ts
> +    // 値のチェック
既存のデータがない場合もエラーになってしまうので、その場合はから配列で処理するようにお願いします。

2022-01-14 08:39 UTC, tingtt commented on src/utils/base/chromeStorage.ts
> +    return objects as T[]
コールバック内でreturnしても関数の戻り地にはならないので、コールバックをgetAll関数の引数に渡せるようにしないといけないです。

2022-01-14 08:39 UTC, tingtt commented on src/utils/base/chromeStorage.ts
> +    return chromeObject[index]
コールバック内でreturnしても (ry

2022-01-19 00:39 UTC, K-shir0 commented on src/utils/base/chromeStorage.ts
> +    // 値のチェック
既存のデータがない場合というのはどういう感じですかね？あんまりよく分かってない

2022-01-19 00:40 UTC, K-shir0 commented
@tingtt 1カ所以外の修正を行いました。

2022-01-19 07:58 UTC, tingtt approved these changes
LGTM

2022-01-19 07:58 UTC, merged