popupの保存済みリストの実行をできるようにした。
indoor-m/hotcale pull request #57
Opened 2022-01-28 14:20 UTC by tomatoaas

ご確認お願い致します。

2022-01-28 14:39 UTC, K-shir0 requested changes
@tomatoaas  確認しました。

これ量が多くなると広がるので不自然ですね。 使いやすさ > 見た目 のなので標準の Select を良さそうなんじゃないでしょうか？

![image](https://user-images.githubusercontent.com/50326556/151565054-e7e59aab-f06f-4a58-9bb5-61ec4dc2b9d1.png)

2022-01-28 14:39 UTC, K-shir0 commented on src/popup.tsx
> +                <>
<> は冗長ですね

2022-01-28 15:24 UTC, tingtt requested changes

2022-01-28 15:24 UTC, tingtt commented on src/popup.tsx
> +    reloadTour()
40行目に同じ処理あｒｙ

2022-01-28 15:24 UTC, tingtt commented on src/popup.tsx
> +        {/* <!-- Dropdown menu --> */}
できれば`position: absolute`にしてポップアップの高さに影響せずにひとつ上のレイヤーでドロップダウンを表示してほしい

あとついでに下のテスト用の巡回開始ボタンとborder消してもらえると助かる

2022-01-28 16:15 UTC, tingtt commented on src/popup.tsx
> +        {/* <!-- Dropdown menu --> */}
試してみたけど結構むずそう・・・
厳しかったらselectで

2022-01-29 03:38 UTC, tomatoaas commented on src/popup.tsx
> +                <>
@K-shir0 
冗長ってどういうこと？
devで囲めってこと？

2022-01-29 03:40 UTC, K-shir0 commented on src/popup.tsx
> +                <>
```
<>
```

2022-01-29 03:42 UTC, K-shir0 commented on src/popup.tsx
> +                <>
冗長はそのままの意味です

2022-01-30 02:25 UTC, tomatoaas commented
プルダウンしたときのオレンジ色にならへん

2022-01-30 11:49 UTC, K-shir0 requested changes
@tomatoaas 
動作確認しましたが、選択しても動かないみたいです。
あとポップアップを表示したときに選択しないも選択肢に含ませて欲しいです。

2022-01-31 04:13 UTC, tingtt approved these changes

2022-01-31 04:13 UTC, K-shir0 approved these changes

2022-01-31 04:13 UTC, merged